In [3]:
import numpy as np

In [19]:
v1 = np.array([10,6,7])
v2 = np.array([10,6,7])
v2 = np.array(5)
print(v1.shape)

(3,)

In [12]:
class student:
    def __init__(self, name , age) -> None:

        self._name = name
        self.age = age
    @property
    def name (self):
        return f"{self._name}"

In [17]:
s1 = student("Ahmed",20)
s1.name

'Ahmed'

In [ ]:
vec = [1,2,3,4,5,6]
mat = vec.reshape((2,3))
print(mat)

AttributeError: 'list' object has no attribute 'reshape'

In [22]:
vec = np.array([1,2,3,4])
vec.shape[0]

4

In [24]:
vec = np.array([1,2,3,4])
mat = vec.reshape((vec.shape[0],1))
print(mat)

[[1]
 [2]
 [3]
 [4]]

In [25]:
vec = np.array([1,2,3,4])
mat = vec[:,None]
print(mat)

[[1]
 [2]
 [3]
 [4]]

In [26]:
def array_reshape(arr, row = -1, cols = -1):
    try:
        arr = np.array(arr)
        return arr.reshape((row, cols))
    except Exception as e:
        raise ValueError("Envalid Reshape operation:{e}")

In [27]:
vec = [1,2,3,4,5,6]
print("test 1(2*3 matrix):", array_reshape(vec, 2, 3))

test 1(2*3 matrix): [[1 2 3]
 [4 5 6]]

In [ ]:
mat = np.array([[1,2,3],[4,5,True]])
mat.dtype

dtype('int64')

In [ ]:
object m, string, float, int, bool, complex

In [36]:
mat = np.array([[7,2,3],[4,5,True]])
fmat = mat.astype(float)
print(fmat) 
print(fmat.dtype)

[[7. 2. 3.]
 [4. 5. 1.]]
float64

In [38]:
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [0, 0, 0]])

m[-3:-1, -3:-1]

array([[4, 5],
       [7, 8]])

In [39]:
mean_filter = np.full((3, 3), 5)
mean_filter

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [40]:
mean_filter = np.empty((3, 3))
mean_filter

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
mat = np.ones((3,3))

In [ ]:
class Teacher:


class Student:

    def __init__(self,name) -> None:
        self. _name = name

In [ ]:
class Student:
    def __init__(self, name) -> None:
        self.__name = name

    @property
    def name(self):
        return self.__name
    @name.setter
    def name(self, value):
        return self.__name = value

s1 = Student("Ahmed")
s1.name

'Ahmed'

In [4]:
vec = np.linspace(0, 10, num = 25)
mat = vec.reshape(5,5)
mat

array([[ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667],
       [ 2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ],
       [ 4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333],
       [ 6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667],
       [ 8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ]])

In [ ]:
I = np.identity()

In [ ]:
a = ['Ahmed', 'Abdo','Omar']

In [5]:
import numpy as np

m1 = np.array([[1, 2, 3],
               [0, 0, 0]])

m2 = np.array([[5, 6, 7],
               [1, 1, 1]])

mat3 = np.hstack((m1, m2))

mat3

array([[1, 2, 3, 5, 6, 7],
       [0, 0, 0, 1, 1, 1]])

In [6]:
s = 4
v = np.array([2, 4, 3, 4, 10])

# v == s
v.__eq__(s)

v.__lt__

In [ ]:
class Student:

    def add(self, a):
        return a

    def add(self, a, b):
        return a + b

In [7]:
class Student:
    def __init__(self, name) -> None:
        self.name = name

    def __eq__(self, value: object) -> bool:
        pass


s1 = Student("Ahmed")
s2 = Student("Abdo")

s1 == s2

In [8]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([2, 3, 0, 5, 3])
np.allclose(v1, v2, atol=1)

False

In [9]:
def is_close(v1, v2) -> bool:
    np.allclose(v1, v2, atol=1)
    np.isclose(v1, v2, atol=1)

In [15]:
v = np.array([2, 4, 3, 4, 10])
condition = v >= 4
new_arr = np.where(condition, -1,v)

print(v)

[ 2  4  3  4 10]

In [17]:
v11 = np.array([1, 2, 3])
c = 2
summation = v11 + c
multiplication = v11 * c
print(summation)
print(multiplication)

[3 4 5]
[2 4 6]

In [18]:
mat1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
v22 = np.array([0.5, 0.5, 0.1])
matrix3 = mat1 * v22
print(matrix3)

[[0.5 1.  0.3]
 [2.  2.5 0.6]
 [3.5 4.  0.9]]

In [19]:
from scipy.sparse import csr_matrix, csc_matrix

mat = np.array([[1, 0, 0, 1, 0, 0],
                [0, 2, 0, 0, 0, 0],
                [0, 0, 0, 2, 0, 0]])

smat = csr_matrix(mat)
smat

ModuleNotFoundError: No module named 'scipy'

In [21]:
import pandas as pd

In [22]:
data = [[1, 444, 'abc'],
        [2, 555, 'def'],
        [3, 666, 'ghi'],
        [4, 444, 'xyz']]

df = pd.DataFrame(data, columns=["Idx", "std_id", "depart"])
df

   Idx  std_id depart
0    1     444    abc
1    2     555    def
2    3     666    ghi
3    4     444    xyz

In [23]:
display(df)

columns = ["idx-1", "std_id", "dep"]
df.columns = columns

display(df)

   Idx  std_id depart
0    1     444    abc
1    2     555    def
2    3     666    ghi
3    4     444    xyz

   idx-1  std_id  dep
0      1     444  abc
1      2     555  def
2      3     666  ghi
3      4     444  xyz