In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("insurance.csv")

In [25]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [29]:
df.info()

<class 'pandas.DataFrame'>
Index: 1337 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1337 non-null   int64
 1   sex       1337 non-null   str
 2   bmi       1337 non-null   float64
 3   children  1337 non-null   int64
 4   smoker    1337 non-null   str
 5   region    1337 non-null   str
 6   charges   1337 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 83.6 KB

In [32]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(1)

In [9]:
df = df.drop_duplicates()

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
print("Sex:", df["sex"].unique())
print("Smoker:", df["smoker"].unique())
print("Region:", df["region"].unique())

Sex: <StringArray>
['female', 'male']
Length: 2, dtype: str
Smoker: <StringArray>
['yes', 'no']
Length: 2, dtype: str
Region: <StringArray>
['southwest', 'southeast', 'northwest', 'northeast']
Length: 4, dtype: str

In [12]:
X = df.drop("charges", axis=1)
y = df["charges"]

In [13]:
print("X:")
print(X.head())

print("\nY:")
print(y.head())

X:
   age     sex     bmi  children smoker     region
0   19  female  27.900         0    yes  southwest
1   18    male  33.770         1     no  southeast
2   28    male  33.000         3     no  southeast
3   33    male  22.705         0     no  northwest
4   32    male  28.880         0     no  northwest

Y:
0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [14]:
X = pd.get_dummies(
    X,
    columns=["sex", "smoker", "region"],
    dtype=int
)

In [16]:
X.head()

,age,bmi,children,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,1,0,0,1,0,0,0,1
1,18,33.770,1,0,1,1,0,0,0,1,0
2,28,33.000,3,0,1,1,0,0,0,1,0
3,33,22.705,0,0,1,1,0,0,1,0,0
4,32,28.880,0,0,1,1,0,0,1,0,0

In [17]:
X.dtypes

age                   int64
bmi                 float64
children              int64
sex_female            int64
sex_male              int64
smoker_no             int64
smoker_yes            int64
region_northeast      int64
region_northwest      int64
region_southeast      int64
region_southwest      int64
dtype: object

In [18]:
y.dtype

dtype('float64')

In [19]:
df.describe()

               age          bmi     children       charges
count  1337.000000  1337.000000  1337.000000   1337.000000
mean     39.222139    30.663452     1.095737  13279.121487
std      14.044333     6.100468     1.205571  12110.359656
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.290000     0.000000   4746.344000
50%      39.000000    30.400000     1.000000   9386.161300
75%      51.000000    34.700000     2.000000  16657.717450
max      64.000000    53.130000     5.000000  63770.428010

In [20]:
numeric_cols = ["age", "bmi", "children"]

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    
    print(f"{col}: {len(outliers)} outliers")

age: 0 outliers
bmi: 9 outliers
children: 0 outliers

In [21]:
Q1 = df["bmi"].quantile(0.25)
Q3 = df["bmi"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

bmi_outliers = df[
    (df["bmi"] < lower_bound) |
    (df["bmi"] > upper_bound)
]

bmi_outliers[["age", "bmi", "children", "smoker", "charges"]]

      age    bmi  children smoker      charges
116    58  49.06         0     no  11381.32540
286    46  48.07         2     no   9432.92530
401    47  47.52         1     no   8083.91980
543    54  47.41         0    yes  63770.42801
847    23  50.38         1     no   2438.05520
860    37  47.60         2    yes  46113.51100
1047   22  52.58         1    yes  44501.39820
1088   52  47.74         1     no   9748.91060
1317   18  53.13         0     no   1163.46270

In [22]:
print("X shape:", X.shape)
print("Y shape:", y.shape)

print("\nX data types:")
print(X.dtypes)

print("\nY data type:")
print(y.dtype)

X shape: (1337, 11)
Y shape: (1337,)

X data types:
age                   int64
bmi                 float64
children              int64
sex_female            int64
sex_male              int64
smoker_no             int64
smoker_yes            int64
region_northeast      int64
region_northwest      int64
region_southeast      int64
region_southwest      int64
dtype: object

Y data type:
float64

In [23]:
print("Missing values in X:")
print(X.isnull().sum().sum())

print("\nMissing values in Y:")
print(y.isnull().sum())

Missing values in X:
0

Missing values in Y:
0

In [24]:
print("Final X shape:", X.shape)
print("Final Y shape:", y.shape)

print("\nX data types:")
print(X.dtypes)

print("\nY data type:")
print(y.dtype)

print("\nMissing values in X:", X.isnull().sum().sum())
print("Missing values in Y:", y.isnull().sum())

Final X shape: (1337, 11)
Final Y shape: (1337,)

X data types:
age                   int64
bmi                 float64
children              int64
sex_female            int64
sex_male              int64
smoker_no             int64
smoker_yes            int64
region_northeast      int64
region_northwest      int64
region_southeast      int64
region_southwest      int64
dtype: object

Y data type:
float64

Missing values in X: 0
Missing values in Y: 0